export default [{
    // LastName
    name: 'LN',
    label: 'Фамилия',
    field: 'LN',
    sortable: true,
    align: 'left',
}, {
    // FirstName
    name: 'FN',
    label: 'Имя',
    field: 'FN',
    sortable: true,
    align: 'left',
}, {
    // FathersName
    name: 'FthN',
    label: 'Отчество',
    field: 'FthN',
    sortable: true,
    align: 'left',
}, {
    name: 'Code',
    label: 'Код',
    field: 'Code',
    sortable: true,
    align: 'left',
}, {
    // BirdthDay
    name: 'BD',
    label: 'Дата рождения',
    field: 'BD',
    sortable: true,
    align: 'left',
}, {
    // CurrentSeparateDivision
    name: 'CSD',
    label: 'Подразделение',
    field: 'CSD',
    sortable: true,
    align: 'left',
}, {
    // CurrentPosition
    name: 'CP',
    label: 'Должность',
    field: 'CP',
    sortable: true,
    align: 'left',
}];
