# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm -v
          - node -v
  branches:
    master:
      - step:
          name: 'Deploy to production'
          deployment: production
          script:
            - pipe: atlassian/ssh-run:0.2.5
              variables:
                SSH_USER: 'www-git'
                SERVER: 'mstroy.tech'
                COMMAND: './scripts/app.mstroy.tech/app.mstroy.tech_build.sh'