query allRolesQuery {
    allRoles {
        rowId
        name
        description
        scenarios {
            rowId
            name
            rootName
            description
        }
    }
}
