#import "./AccessGroupsFragment.gql"

mutation createAccessGroupMutation($input: CreateAccessGroupInput!) {
    createAccessGroup(input: $input) {
        ok
        accessgroup {
            ...AccessGroupsFragment
        }
    }
}
