query allTimeResourcesQuery($filters: TimeResourceFilter) {
    allTimeResources(filters: $filters) {
        rowId
        name
        projectId
        worker {
            rowId
            lastName
            firstName
            surname
            position {
                rowId
                name
            }
        }
    }
}
